# Generated by Django 5.0.6 on 2024-05-21 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=10)),
                ('setor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_projeto', models.CharField(max_length=30)),
                ('numero_sei', models.CharField(max_length=21)),
                ('numero_parcela', models.CharField(max_length=20)),
                ('valor_solicitado', models.FloatField()),
                ('titulo_projeto', models.CharField(max_length=100)),
                ('status_transacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField()),
                ('data_conferencia_documentos', models.DateTimeField()),
                ('data_autorizacao_empenho', models.DateTimeField()),
                ('data_confeccao_empenho', models.DateTimeField()),
                ('numero_empenho', models.CharField(max_length=30)),
                ('data_confeccao_termo', models.DateTimeField()),
                ('data_envio_termo', models.DateTimeField()),
                ('numero_termo', models.CharField(max_length=30)),
                ('responsavel_confeccao', models.CharField(max_length=100)),
                ('data_visto_termo', models.DateTimeField()),
                ('data_envio_term_proponente', models.DateTimeField()),
                ('data_assinatura_termo', models.DateTimeField()),
                ('data_envio_pagamento', models.DateTimeField()),
                ('data_ordem_bancaria', models.DateTimeField()),
                ('status_transacao', models.CharField(max_length=100)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transacao', models.DateTimeField()),
                ('status_transacao', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cadastrousuario')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='transacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transacao'),
        ),
    ]
