from django.urls import path
from django.contrib import admin

from app.views import (
    home,
    usuarios_html,
    transacao_html,
    projeto_html,
    processo_html,
    form_login,
    form_logout,
    form_cadastro_usuario,
    form_transacao,
    form_processo,
    form_projeto,
    edit_usuario,
    edit_projeto,
    edit_processo,
    view_usuario,
    view_transacao,
    view_projeto,
    view_processo,
    delete_usuario,
    delete_transacao,
    delete_projeto,
    delete_processo,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home, name='home'),
    path("", form_login, name="login"),
    path("logout/", form_logout, name="logout"),
    path("usuarios_html/", usuarios_html, name="usuarios_html"),
    path("transacao_html/", transacao_html, name="transacao_html"),
    path("projeto_html/", projeto_html, name="projeto_html"),
    path("processo_html/", processo_html, name="processo_html"),
    path("form_cadastro_usuario/", form_cadastro_usuario, name="form_cadastro_usuario"),
    path("form_transacao/", form_transacao, name="form_transacao"),
    path("form_projeto/", form_projeto, name="form_projeto"),
    path("form_processo/", form_processo, name="form_processo"),
    path("edit_usuario/<int:usuario_id>/", edit_usuario, name="edit_usuario"),
    path("edit_projeto/<int:projeto_id>/", edit_projeto, name="edit_projeto"),
    path("edit_processo/<int:processo_id>/", edit_processo, name="edit_processo"),
    path("view_usuario/<int:usuario_id>/", view_usuario, name="view_usuario"),
    path("view_transacao/<int:transacao_id>/", view_transacao, name="view_transacao"),
    path("view_projeto/<int:projeto_id>/", view_projeto, name="view_projeto"),
    path("view_processo/<int:processo_id>/", view_processo, name="view_processo"),
    path("delete_usuario/<int:id>/", delete_usuario, name="delete_usuario"),
    path("delete_transacao/<int:id>/", delete_transacao, name="delete_transacao"),
    path("delete_projeto/<int:id>/", delete_projeto, name="delete_projeto"),
    path("delete_processo/<int:id>/", delete_processo, name="delete_processo"),
]
